package org.vaadin.challenges.datamanipulation;

public enum CategoriesWithIdsEnum {
    ADVENTURE_TRAVEL(0),
    SUSTAINABLE_LIVING(1),
    VIRTUAL_REALITY(2),
    CYBERSECURITY(3),
    GOURMET_COOKING(4),
    MINDFULNESS_MEDITATION(5),
    URBAN_GARDENING(6),
    DIY_CRAFTS(7),
    ASTROPHYSICS(8),
    VINTAGE_FASHION(9),
    EXTREME_SPORTS(10),
    RENEWABLE_ENERGY(11),
    GRAPHIC_DESIGN(12),
    MARINE_BIOLOGY(13),
    INDIE_MUSIC(14),
    HOME_AUTOMATION(15),
    CULTURAL_ANTHROPOLOGY(16),
    MOBILE_PHOTOGRAPHY(17),
    ARTIFICIAL_INTELLIGENCE(18),
    SLOW_FASHION(19),
    SPACE_EXPLORATION(20),
    ETHICAL_INVESTING(21),
    STREET_ART(22),
    RENEWABLE_AGRICULTURE(23),
    ROBOTICS(24),
    WORLD_HISTORY(25),
    INTERIOR_DESIGN(26),
    FITNESS_TECHNOLOGY(27),
    SUSTAINABLE_ARCHITECTURE(28),
    QUANTUM_MECHANICS(29),
    FOOD_SCIENCE(30),
    STAND_UP_COMEDY(31),
    ALTERNATIVE_MEDICINE(32),
    URBAN_FARMING(33),
    DIY_ELECTRONICS(34),
    OUTDOOR_ADVENTURE(35),
    POLITICAL_SATIRE(36),
    BEHAVIORAL_ECONOMICS(37),
    RETRO_GAMING(38),
    AUGMENTED_REALITY(39),
    CRYPTOCURRENCY(40),
    SUSTAINABLE_TRANSPORTATION(41),
    CREATIVE_WRITING(42),
    ANCIENT_HISTORY(43),
    DIY_HOME_IMPROVEMENT(44),
    ASTRONOMY(45),
    INDIE_FILMMAKING(46),
    PERSONAL_FINANCE(47),
    VINTAGE_CARS(48),
    MARINE_CONSERVATION(49);

    private final int id;

    CategoriesWithIdsEnum(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }
}